export const MARK_TASK_AS_COMPLETE = 'MARK_TASK_AS_COMPLETE';
export const MARK_TASK_AS_IMPORTANT = 'MARK_TASK_AS_IMPORTANT';
export const DELETE_TASK_FROM_LIST = 'DELETE_TASK_FROM_LIST';
export const ADD_DATA_TO_LIST = 'ADD_DATA_TO_LIST';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_LOGIN_STATUS_TO_ACTIVE = 'SET_LOGIN_STATUS_TO_ACTIVE';